# Generated by Django 5.0.7 on 2024-09-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
                ('hostName', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=50)),
                ('Venue', models.CharField(max_length=50)),
            ],
        ),
    ]
